name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create config file
      run: |
        cat > js/config.js << EOF
        // Google Maps API Configuration
        const MAPS_CONFIG = {
            API_KEY: '${{ secrets.GOOGLE_MAPS_API_KEY }}',
            STUDIO_LOCATION: {
                lat: 35.6870,
                lng: -105.9378
            },
            STUDIO_ADDRESS: '528 Jose Street, Santa Fe, NM 87501'
        };
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . 